version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install AWS CLI
          command: |
            sudo apt update
            sudo apt install -y unzip
            sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo unzip awscliv2.zip
            sudo ./aws/install
            aws --version
      - run:
          name: Deploy function.zip to AWS Lambda
          command: |
            RELEASE_TAG=release-circleci-${CIRCLE_BUILD_NUM}
            aws lambda update-function-code --function-name bbb --zip-file fileb:///tmp/workspace/function.zip --publish --region eu-west-1
            aws lambda tag-resource --resource arn:aws:lambda:eu-west-1:330065802977:function:bbb --tags release=${RELEASE_TAG}

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - gradle/test:
          with_cache:
            steps:
               - run:
                  name: Build and test
                  command: ./gradlew build --no-daemon
          store_artifacts: build/function.zip
      - build_and_test
      - deploy:
          context: aws-root-key
          requires:
            - build_and_test
          filters:
            branches:
              only: main
