name: Deploy Function

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Download function.zip from release
      run: |
        curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.releaseTag }} \
        | grep "browser_download_url.*zip" \
        | cut -d '"' -f 4 \
        | wget -i - -O function.zip

    - name: Deploy function.zip to AWS Lambda
      run: aws lambda update-function-code --function-name bbb --zip-file fileb://function.zip
