name: Deploy Function

on:
  workflow_run:
    workflows: ["Gradle Build and Test"]
    branches:
      - main
    types:
      - completed
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        
    - name: Download function.zip from release
      if: ${{ github.event_name == 'workflow_run' }}
      run: |
        if [ "${{ github.event_name }}" = "workflow_run" ]; then
          RELEASE_TAG=release-${{ github.event.workflow_run.run_number }}
        else
          RELEASE_TAG=${{ github.event.inputs.releaseTag }}
        fi
        curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${RELEASE_TAG} \
        | grep "browser_download_url.*zip" \
        | cut -d '"' -f 4 \
        | wget -i - -O function.zip

    - name: Deploy function.zip to AWS Lambda
      run: aws lambda update-function-code --function-name bbb --zip-file fileb://function.zip
      
    - name: Tag AWS Lambda function
      run: |
        if [ "${{ github.event_name }}" = "workflow_run" ]; then
          RELEASE_TAG=release-${{ github.event.workflow_run.run_number }}
        else
          RELEASE_TAG=${{ github.event.inputs.releaseTag }}
        fi
        aws lambda tag-resource --resource arn:aws:lambda:eu-west-1:330065802977:function:bbb --tags release=${RELEASE_TAG}
